quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=docpass
quarkus.datasource.password=docpass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/docpass

quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=false

quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

quarkus.log.console.json.enabled=true
quarkus.log.console.json=false
quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.console.json.pretty-print=false

kafka.bootstrap.servers=localhost:9092

mp.messaging.outgoing.perfil_atualizado.connector=smallrye-kafka
mp.messaging.outgoing.perfil_atualizado.topic=perfil_atualizado
mp.messaging.outgoing.perfil_atualizado.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.documento_enviado.connector=smallrye-kafka
mp.messaging.outgoing.documento_enviado.topic=documento_enviado
mp.messaging.outgoing.documento_enviado.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.outgoing.consentimento_concedido.connector=smallrye-kafka
mp.messaging.outgoing.consentimento_concedido.topic=consentimento_concedido
mp.messaging.outgoing.consentimento_concedido.value.serializer=org.apache.kafka.common.serialization.StringSerializer

mp.messaging.incoming.perfil_atualizado_in.connector=smallrye-kafka
mp.messaging.incoming.perfil_atualizado_in.topic=perfil_atualizado
mp.messaging.incoming.perfil_atualizado_in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.incoming.documento_enviado_in.connector=smallrye-kafka
mp.messaging.incoming.documento_enviado_in.topic=documento_enviado
mp.messaging.incoming.documento_enviado_in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

mp.messaging.incoming.consentimento_concedido_in.connector=smallrye-kafka
mp.messaging.incoming.consentimento_concedido_in.topic=consentimento_concedido
mp.messaging.incoming.consentimento_concedido_in.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

quarkus.s3.endpoint-override=http://localhost:9000
quarkus.s3.aws.region=us-east-1
quarkus.s3.path-style-access=true
quarkus.s3.aws.credentials.type=static
quarkus.s3.aws.credentials.static-provider.access-key-id=minioadmin
quarkus.s3.aws.credentials.static-provider.secret-access-key=minioadmin

docpass.storage.bucket=docpass-docs

mp.jwt.verify.publickey.location=http://localhost:8081/realms/docpass/protocol/openid-connect/certs
mp.jwt.verify.issuer=http://localhost:8081/realms/docpass

quarkus.smallrye-jwt.enabled=true
