ALTER TABLE users
    ADD COLUMN IF NOT EXISTS nome_completo VARCHAR(120);

UPDATE users SET nome_completo = nome WHERE nome_completo IS NULL;

ALTER TABLE users
    ALTER COLUMN nome_completo SET NOT NULL;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS nome_social VARCHAR(120),
    ADD COLUMN IF NOT EXISTS genero VARCHAR(30),
    ADD COLUMN IF NOT EXISTS sexo VARCHAR(20),
    ADD COLUMN IF NOT EXISTS estado_civil VARCHAR(30),
    ADD COLUMN IF NOT EXISTS nacionalidade VARCHAR(120),
    ADD COLUMN IF NOT EXISTS naturalidade VARCHAR(120),
    ADD COLUMN IF NOT EXISTS nome_mae VARCHAR(120),
    ADD COLUMN IF NOT EXISTS nome_pai VARCHAR(120),
    ADD COLUMN IF NOT EXISTS rg_numero VARCHAR(40),
    ADD COLUMN IF NOT EXISTS rg_orgao_emissor VARCHAR(40),
    ADD COLUMN IF NOT EXISTS rg_estado_emissor VARCHAR(2),
    ADD COLUMN IF NOT EXISTS rg_data_emissao DATE,
    ADD COLUMN IF NOT EXISTS cnh_numero VARCHAR(40),
    ADD COLUMN IF NOT EXISTS cnh_categoria VARCHAR(5),
    ADD COLUMN IF NOT EXISTS cnh_validade DATE,
    ADD COLUMN IF NOT EXISTS titulo_eleitor_numero VARCHAR(40),
    ADD COLUMN IF NOT EXISTS passaporte_numero VARCHAR(40),
    ADD COLUMN IF NOT EXISTS logradouro VARCHAR(200),
    ADD COLUMN IF NOT EXISTS numero VARCHAR(50),
    ADD COLUMN IF NOT EXISTS complemento VARCHAR(120),
    ADD COLUMN IF NOT EXISTS bairro VARCHAR(120),
    ADD COLUMN IF NOT EXISTS cidade VARCHAR(120),
    ADD COLUMN IF NOT EXISTS estado VARCHAR(2),
    ADD COLUMN IF NOT EXISTS cep VARCHAR(9),
    ADD COLUMN IF NOT EXISTS pais VARCHAR(2),
    ADD COLUMN IF NOT EXISTS profissao VARCHAR(120),
    ADD COLUMN IF NOT EXISTS empresa_atual VARCHAR(180),
    ADD COLUMN IF NOT EXISTS renda_mensal NUMERIC(14, 2),
    ADD COLUMN IF NOT EXISTS tipo_sanguineo VARCHAR(20),
    ADD COLUMN IF NOT EXISTS time_que_torce VARCHAR(120),
    ADD COLUMN IF NOT EXISTS foto_perfil_url TEXT,
    ADD COLUMN IF NOT EXISTS biografia TEXT,
    ADD COLUMN IF NOT EXISTS linkedin TEXT,
    ADD COLUMN IF NOT EXISTS instagram TEXT,
    ADD COLUMN IF NOT EXISTS twitter TEXT,
    ADD COLUMN IF NOT EXISTS github TEXT;
